component: website
name: site

inputs:
  # React application. "hook" runs before deployment to build the source code.  "dist" is the built artifact directory which is uploaded.
  domain: ${env:domain}
  src:
    src: ./
    hook: npm run build
    dist: build
    

